let lore = {
  "LEA": "We’ll start back at the very beginning, when Ye Holy Father Garfield and his team at Wizards released the first ever Magic set, Limited Edition, which included what we know as Alpha and Beta, nicknames for each of the print runs of this set. It didn’t have any real storyline other than the concept that the players were powerful planeswalkers dueling each other. After the initial print run (Alpha), there was more demand than expected so they ran two additional runs, now known as Beta and the first white-bordered set, Unlimited. White borders were introduced as a way of marking ‘reprint’ sets.",
  "LEB": "We’ll start back at the very beginning, when Ye Holy Father Garfield and his team at Wizards released the first ever Magic set, Limited Edition, which included what we know as Alpha and Beta, nicknames for each of the print runs of this set. It didn’t have any real storyline other than the concept that the players were powerful planeswalkers dueling each other. After the initial print run (Alpha), there was more demand than expected so they ran two additional runs, now known as Beta and the first white-bordered set, Unlimited. White borders were introduced as a way of marking ‘reprint’ sets.",
  "2ED": "We’ll start back at the very beginning, when Ye Holy Father Garfield and his team at Wizards released the first ever Magic set, Limited Edition, which included what we know as Alpha and Beta, nicknames for each of the print runs of this set. It didn’t have any real storyline other than the concept that the players were powerful planeswalkers dueling each other. After the initial print run (Alpha), there was more demand than expected so they ran two additional runs, now known as Beta and the first white-bordered set, Unlimited. White borders were introduced as a way of marking ‘reprint’ sets.",
  "ARN": "The story of Arabian Nights is set on one of the planes of Rabiah, which experienced an event called the Thousandfold Refraction, creating one thousand and one identical planes. The story told the life of the planeswalker Taysir – he was refracted into five pieces by the Thousandfold Refraction, and manipulated by Queen Naliah into becoming one again, reigniting his planeswalker spark. He chose to leave, however, and Naliah afterwards cast a spell that prevented planeswalkers from ever coming to the 1001 versions of Rabiah ever again.",
  "ATQ": "This set returns to the original setting of the game, Dominaria, and covers the Brothers’ War between Urza and Mishra, two powerful artificers. After an accident which killed their tutor when they were young, they separated, and Mishra became corrupted with Phyrexian technology through the machinations of Gix, Yawgmoth’s servant. Mishra fought Urza for forty years in an ongoing conflict that divided the nation. It ended when Urza activated the Golgothian Sylex, which released a blast wave that caused Urza to gain his planeswalker spark, Mishra to perish, and most of the civilisations on Dominaria to be wiped out, causing the beginning of the Dark Age.",
  '3ED': 'Revised Edition was a reprint set, indicated by its white borders, to bring more copies of the ‘core’ cards into circulation. They also took the opportunity to solidify the rules into a physical guide. It was the first set to be printed in French and German as well as English.',
  'LEG': 'This was the brainchild of two Magic fans introduced to the game by Garfield and later recruited to Wizards’ development team. It was the first set to include multicoloured cards, and mainly consisted of the game’s legendary creatures and places and their individual stories, rather than one overarching tale. Nicol Bolas makes his first appearance here, in the cycle of Elder Dragons.',
  'DRK': 'The Dark takes us back to Dominaria, picking up after the Sylex blast. The debris blots out the sun, creating a Dark Age where a new anti-magic religion has risen after mages were blamed for the disaster. They are holed up in the Conclave of Mages to the west, while dark powers rule in the City of Shadows to the east. During the set, there are conflicts between the two strongholds, while the other creatures of Dominaria – thrulls, goblins, orcs, merfolk and homarids – struggle for control of the wilderness between them.',
  'FEM': 'This continues the storyline somewhat from The Dark. This set focuses less on the conflict between the wizards and the powers-that-be, and more on the non-human races and their existence in the ruined cities destroyed by the Sylex blast. The set follows the stories of several different societies and their attempts to vie for power on the ruins of old human settlements. It is also when the goblin tribes migrate south out of the mountains and overthrow the Dwarven empires.',
  'ICE': 'Ice Age began the ‘blocks’ system which was used up until the end of Ixalan block. We are still on Dominaria, and an event originally triggered by the Sylex blast has now finally occurred; the energy of twelve planes fused into The Shard of Twelve Worlds, which encased Dominaria away from the rest of the Multiverse, trapping planeswalkers inside the shard and preventing others from entering it. This caused the beginning of the Ice Age, where all major civilisations have now collapsed from the ongoing wars and the ice. Urza had been corrupted by Yawgmoth after his attempt to stop the Phyrexians failed, and is having his mind healed. The powerful necromancer Lim-Dul is defeated and banished.',
  'CHR': 'Chronicles is one of the most important sets in the history of the game. It had such a massive print run that all the cards which had been reprinted fell heavily in price and were worth very little. Collectors were aghast at the loss of value and many people left the game, feeling that they had been betrayed. This led to the emergency promise that still affects the game today: The Reserved List. Wizards put the remaining cards from Revised edition backwards onto the list and created a formal document stating that they would never reprint these cards again. This brought back a lot of faith from the players, however, nobody could have imagined the repercussions such a promise would have in 20 years’ time – a game lasting that long would be unprecedented.',
  '': '',
}